import { expect, test } from '@playwright/test';

import { signUpAndEnter } from './support';

test.use({ permissions: ['clipboard-read', 'clipboard-write'] });

test('the daily summary: highlight line, tone, generate on-device, copy, and today’s summary restores', async ({
  page,
}) => {
  await signUpAndEnter(page, 'summary');
  await page
    .getByRole('region', { name: 'Best next move' })
    .getByRole('button', { name: 'Close it' })
    .click();
  await expect(page.getByRole('img', { name: '1 of 5 closed today' })).toBeVisible();

  await page.goto('/today/week-review');
  const summary = page.getByRole('region', { name: 'Daily summary' });
  await expect(summary.getByRole('heading', { name: 'Daily Executive Summary' })).toBeVisible();
  await expect(summary.getByRole('list', { name: 'Today in numbers' })).toContainText('Open Tasks');
  // Before anything is generated: the honest highlight line from today's counts.
  await expect(
    summary.getByText(/open tasks? across \d+ areas? — start with the smallest one\./),
  ).toBeVisible();

  const gentle = summary.getByRole('button', { name: 'Gentle' });
  await gentle.click();
  await expect(gentle).toHaveAttribute('aria-pressed', 'true');
  await summary.getByRole('button', { name: 'Generate' }).click();

  const card = summary.getByRole('article', { name: 'Generated summary' });
  await expect(card.getByText('You closed 1 today. That was enough.')).toBeVisible();
  await expect(card.getByText('You finished Take a 10-minute walk.')).toBeVisible();
  await expect(card.getByLabel('Generated by On-device synthesis, Gentle tone')).toBeVisible();
  await expect(summary.getByRole('button', { name: 'Regenerate' })).toBeVisible();

  await card.getByRole('button', { name: 'Copy' }).click();
  await expect(card.getByRole('button', { name: 'Copied' })).toBeVisible();
  const copied = await page.evaluate(() => navigator.clipboard.readText());
  expect(copied).toContain('✨ ADHD LifeOS Daily Summary (');
  expect(copied).toContain('🏆 Dopamine Wins:\n• You finished Take a 10-minute walk.');

  // Today's summary and its tone come back on the next visit.
  await page.reload();
  await expect(
    page
      .getByRole('region', { name: 'Daily summary' })
      .getByText('You closed 1 today. That was enough.'),
  ).toBeVisible();
  await expect(
    page.getByRole('region', { name: 'Daily summary' }).getByRole('button', { name: 'Gentle' }),
  ).toHaveAttribute('aria-pressed', 'true');
});
