#!/usr/bin/env python3
"""Generate src/theme/tokens.css and src/theme/tokens.ts from the iOS asset catalog.

Usage: python3 scripts/gen-tokens.py "<path to ADHD LifeOS/Assets.xcassets>"

The iOS app is the source of truth for the palette (CLAUDE.md there, §4: hex lives only in the
asset catalog). This script is the web equivalent of that rule: hex lives only in the generated
files, and views consume tokens through Tailwind's @theme names.
"""
import glob
import json
import os
import re
import sys

if len(sys.argv) != 2:
    sys.exit(__doc__)
catalog = sys.argv[1]
if not os.path.isdir(catalog):
    sys.exit(f"not a directory: {catalog}")


def channel(v):
    v = str(v)
    if v.startswith("0x"):
        return int(v, 16)
    f = float(v)
    return round(f * 255) if f <= 1.0 else int(f)


def css_color(c):
    comp = c["color"]["components"]
    r, g, b = channel(comp["red"]), channel(comp["green"]), channel(comp["blue"])
    a = float(comp.get("alpha", "1"))
    if a >= 0.999:
        return "#%02X%02X%02X" % (r, g, b)
    return "rgb(%d %d %d / %s)" % (r, g, b, ("%.2f" % a).rstrip("0").rstrip("."))


def kebab(name):
    if name == "AccentColor":
        return "accent"
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


rows = []
for d in sorted(glob.glob(os.path.join(catalog, "**", "*.colorset"), recursive=True)):
    swift = os.path.basename(d)[: -len(".colorset")]
    data = json.load(open(os.path.join(d, "Contents.json")))
    light = dark = None
    for c in data.get("colors", []):
        appearances = c.get("appearances", [])
        if any(a.get("value") == "dark" for a in appearances):
            dark = css_color(c)
        elif not appearances:
            light = css_color(c)
    if light is None:
        sys.exit(f"{swift}: no light value")
    rows.append((kebab(swift), swift, light, dark or light))

header = "/* Generated by scripts/gen-tokens.py from the iOS asset catalog. Do not edit by hand. */\n"
css = [header, ":root {"]
css += [f"  --lifeos-{n}: {l};" for n, _, l, _ in rows]
css += ["}", "", "@media (prefers-color-scheme: dark) {", "  :root:not([data-theme='light']) {"]
css += [f"    --lifeos-{n}: {d};" for n, _, _, d in rows]
css += ["  }", "}", "", ":root[data-theme='dark'] {"]
css += [f"  --lifeos-{n}: {d};" for n, _, _, d in rows]
css += ["}", "", "/* Tailwind names: bg-page-background, text-label-primary, border-card-border, … */", "@theme inline {"]
css += [f"  --color-{n}: var(--lifeos-{n});" for n, _, _, _ in rows]
css += ["}", ""]

ts = ["// Generated by scripts/gen-tokens.py from the iOS asset catalog. Do not edit by hand.", "",
      "export const COLOR_TOKENS = ["]
ts += [f"  {{ name: '{n}', swift: '{s}', light: '{l}', dark: '{d}' }}," for n, s, l, d in rows]
ts += ["] as const;", "", "export type ColorTokenName = (typeof COLOR_TOKENS)[number]['name'];", "",
       "export function colorToken(name: ColorTokenName, appearance: 'light' | 'dark' = 'light'): string {",
       "  const token = COLOR_TOKENS.find((t) => t.name === name);",
       "  if (!token) throw new Error(`Unknown colour token: ${name}`);",
       "  return appearance === 'dark' ? token.dark : token.light;",
       "}", ""]

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
open(os.path.join(root, "src", "theme", "tokens.css"), "w").write("\n".join(css))
open(os.path.join(root, "src", "theme", "tokens.ts"), "w").write("\n".join(ts))
print(f"wrote {len(rows)} colour tokens")
